services:
  - type: web
    name: crud-demo
    rootDir: demo
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/demo-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
